{% set name = "sapiens" %}
{% set version = "1.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: cec9c0cbc2fb04d27a61ed6468da402d11bc01e52cd74c55d600cbba6271324c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - pandas
    - fairseq ==0.10.2 # using old fairseq version until latest version is on conda-forge
    - numpy <1.24.0 # use old numpy version because of fairseq incompatibility

test:
  imports:
    - sapiens
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/Merck/Sapiens
  summary: 'Sapiens is a human antibody language model based on BERT'
  description: |
    Sapiens is a human antibody language model based on BERT. Sapiens is trained on antibodies from the Observed Antibody Space (OAS).
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - prihoda
