{% set name = "sapiens" %}
{% set version = "1.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 81d5c9930b7eff8563c46ab82c70c44f5bf28ccfc77103df2b10ec92382fe87f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - pandas
    - fairseq

test:
  imports:
    - sapiens
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/Merck/Sapiens
  summary: 'Sapiens is a human antibody language model based on BERT'
  description: |
    Sapiens is a human antibody language model based on BERT. Sapiens is trained on antibodies from the Observed Antibody Space (OAS).
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - prihoda
