{% set name = "sapiens" %}
{% set version = "1.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 805e620398078fa0ea08bbce5493e56acf42653c9f08908a7bcbaa7553daa00b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - pandas
    - fairseq ==0.12.3

test:
  imports:
    - sapiens
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Merck/Sapiens
  summary: 'Sapiens is a human antibody language model based on BERT'
  description: |
    Sapiens is a human antibody language model based on BERT. Sapiens is trained on antibodies from the Observed Antibody Space (OAS).
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - prihoda
