{% set name = "sapiens" %}
{% set version = "1.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3523f7de49362bc908034a8e71f4e30c68a866234c360dcb66cc2b212f8ca6eb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - pandas
    - fairseq ==0.12.3

test:
  imports:
    - sapiens
  requires:
    - pip

about:
  home: https://github.com/Merck/Sapiens
  summary: 'Sapiens is a human antibody language model based on BERT'
  description: |
    Sapiens is a human antibody language model based on BERT. Sapiens is trained on antibodies from the Observed Antibody Space (OAS).
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - prihoda
